"""change passw lenght +

Revision ID: 4a08ace9eeec
Revises: eaecedb3ba54
Create Date: 2024-03-24 13:20:33.622952

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4a08ace9eeec'
down_revision: Union[str, None] = 'eaecedb3ba54'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('comments', 'opinion',
               existing_type=sa.VARCHAR(length=250),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.alter_column('users', 'name',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=30),
               existing_nullable=True)
    op.alter_column('users', 'avatar',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=250),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'avatar',
               existing_type=sa.String(length=250),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('users', 'name',
               existing_type=sa.String(length=30),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
    op.alter_column('comments', 'opinion',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=250),
               existing_nullable=False)
    # ### end Alembic commands ###
