"""add phone

Revision ID: aa1140d969f4
Revises: c66d6701674f
Create Date: 2024-02-12 13:25:36.790129

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'aa1140d969f4'
down_revision: Union[str, None] = 'c66d6701674f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contacts', sa.Column('phone', sqlalchemy_utils.types.phone_number.PhoneNumberType(length=20), nullable=True))
    op.alter_column('contacts', 'email',
               existing_type=sa.VARCHAR(length=80),
               type_=sqlalchemy_utils.types.email.EmailType(length=255),
               nullable=True)
    op.alter_column('contacts', 'birthday',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.Date(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('contacts', 'birthday',
               existing_type=sa.Date(),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('contacts', 'email',
               existing_type=sqlalchemy_utils.types.email.EmailType(length=255),
               type_=sa.VARCHAR(length=80),
               nullable=False)
    op.drop_column('contacts', 'phone')
    # ### end Alembic commands ###
