"""email unique

Revision ID: b843e6ddb2fc
Revises: b6352fcf4bf3
Create Date: 2024-02-12 15:48:45.729907

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b843e6ddb2fc'
down_revision: Union[str, None] = 'b6352fcf4bf3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'contacts', ['email'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'contacts', type_='unique')
    # ### end Alembic commands ###
