"""phone 12 dig

Revision ID: e151f06a5c27
Revises: b843e6ddb2fc
Create Date: 2024-02-13 19:50:06.905887

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e151f06a5c27'
down_revision: Union[str, None] = 'b843e6ddb2fc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('contacts', 'email',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('contacts', 'phone',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=12),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('contacts', 'phone',
               existing_type=sa.String(length=12),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
    op.alter_column('contacts', 'email',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    # ### end Alembic commands ###
