"""Image --> Photo

Revision ID: eaecedb3ba54
Revises: 12db0f47c2c7
Create Date: 2024-03-24 03:44:45.862598

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eaecedb3ba54'
down_revision: Union[str, None] = '12db0f47c2c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('photos', sa.Column('path_transform', sa.String(length=250), nullable=True))
    op.drop_column('photos', 'path_tranform')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('photos', sa.Column('path_tranform', sa.VARCHAR(length=250), autoincrement=False, nullable=False))
    op.drop_column('photos', 'path_transform')
    # ### end Alembic commands ###
