NAME_MIN_LENGTH = 3
NAME_MAX_LENGTH = 30

USERNAME_MIN_LENGTH = 3
USERNAME_MAX_LENGTH = 50
EMAIL_MAX_LENGTH = 150

PASSWORD_MIN_LENGTH = 5
PASSWORD_MAX_LENGTH = 30

TOKEN_MAX_LENGTH = 255

COMMENT_MIN_LENGTH = 5
COMMENT_MAX_LENGTH = 255

RATING_MIN_VALUE = 1
RATING_MAX_VALUE = 5

TAG_MIN_LENGTH = 5
TAG_MAX_LENGTH = 30

PHOTO_PATH_LENGTH = 250
TRANSFORM_PATH_LENGTH = 250
PHOTO_MIN_DESCRIPTION_LENGTH = 5
PHOTO_MAX_DESCRIPTION_LENGTH = 250
AVATAR_PATH_LENGTH = 250